volumes:
  db_data:


services:

  bot:
    image: mustinov77/test_bot_tg:latest
    env_file: .env
    volumes:
      - db_data:/app/data
    command: sh -c "alembic upgrade head && python -m bot.main"
