"""Question.number_of_variants column

Revision ID: 367d73e63165
Revises: 4684d69aea76
Create Date: 2026-03-25 17:53:34.466091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '367d73e63165'
down_revision: Union[str, Sequence[str], None] = '4684d69aea76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('number_of_variants', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'number_of_variants')
    # ### end Alembic commands ###
