- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Создать директорию проекта
  file:
    path: "{{ bot_directory.dir }}"
    state: directory

- name: Download raw file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/MUstinov77/test_bot_tg/main/docker-compose.yml
    dest: "{{ bot_directory.dir }}/docker-compose.yml"

- name: Pull and recreate containers
  community.docker.docker_compose_v2:
    project_src: "{{ bot_directory.dir }}"
    env_files: "{{ bot_directory.dir }}/.env"
    pull: always
    state: present
    recreate: always
