- name: Создать директорию проекта
  file:
    path: "{{ bot_directory }}"
    state: directory

- name: Copy docker-compose
  get_url:
    src: https://raw.githubusercontent.com/MUstinov77/test_bot_tg/main/docker-compose.yml
    dest: "{{ bot_directory }}/docker-compose.yml"
    headers:
      Authorization: "token {{ github_token }}"
- name: Run docker-compose
  tasks:
    - name: Tear down existing services
      community.docker.docker_compose_v2:
        project_src: "{{ bot_directory }}"
        state: absent
        remove_images: "local"
    - name: Run `docker compose up` again
      community.docker.docker_compose_v2:
        project_src: "{{ bot_directory }}"
        env_files: .env
      register: output
