- name: Создать директорию проекта
  file:
    path: "{{ bot_directory }}"
    state: directory

- name: Copy docker-compose
  get_url:
    src: https://api.github.com/repos/MUstinov77/test_bot_tg/contents/docker-compose.yml
    dest: "{{ bot_directory }}/docker-compose.yml"
    headers:
      Authorization: "Bearer '{{ github_token }}'"
      Accept: application/vnd.github.v3.raw

- name: Tear down existing containers
  community.docker.docker_compose_v2:
     project_src: "{{ bot_directory }}"
     state: absent
     remove_images: "local"

- name: Run `docker compose up` again
  community.docker.docker_compose_v2:
    project_src: "{{ bot_directory }}"
    env_files: "{{ bot_directory }}/.env"
  register: output
