- name: Deploy tg bot
  hosts: all
  become: yes


  tasks:
    - name: Run bot role
      include_role:
        name: bot
      loop: "{{ bots_directories }}"
      loop_control:
        loop_var: bot_directory

