name: Main test_bot_tg workflow

on:
  push:
    branches:
      - main

jobs:

  deploy_to_prod:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          server:
            # add server credential here
            - name: "ExpatTestBot"
              user: ${{secrets.USERNAME}}
              host: ${{secrets.EXPAT_SERVER_HOST}}
              password: ${{secrets.EXPAT_SERVER_PASSWORD}}
          fail-fast: false
      steps:
        - name: Checkout repo
          uses: actions/checkout@v5
        - name: Deploy to ${{ matrix.server.name }}
          uses: appleboy/ssh-action@master
          with:
            host: ${{ matrix.server.host }}
            username: ${{ matrix.server.user }}
            password: ${{ matrix.server.password }}
            script: |
              cd bots/test_bot_tg/
              git pull origin main
              sudo systemctl restart bot
        - name: Send message to telegram
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
            message: Deploy test_bot_tg is completed