name: Main test_bot_tg workflow

on:
  push:
    branches:
      - main

jobs:

  deploy_to_prod:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v5
        - name: Deploy to ExpatServer
          uses: appleboy/ssh-action@master
          with:
            username: ${{ secrets.USERNAME }}
            host: ${{ secrets.EXPAT_SERVER_HOST }}
            password: ${{ secrets.EXPAT_SERVER_PASSWORD }}
            script: |
              cd bots/test_bot_tg/
              source .venv/bin/activate
              pip install -r requirements.txt
              git pull origin main
              alembic upgrade head
              sudo systemctl restart bot
        - name: Deploy to Chizhof
          uses: appleboy/ssh-action@master
          with:
            username: ${{ secrets.USERNAME }}
            host: ${{ secrets.CHIZHOF_SERVER_HOST }}
            password: ${{ secrets.CHIZHOF_SERVER_PASSWORD }}
            script: |
              cd bots/test_bot_tg/
              git pull origin main
              source .venv/bin/activate
              pip install -r requirements.txt
              alembic upgrade head
              sudo systemctl restart bot
        - name: Send message to telegram
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
            message: Deploy test_bot_tg is completed